#!/usr/bin/php -q
<?PHP
/* Copyright 2023, IkerSaint
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 2,
 * as published by the Free Software Foundation.
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 */
?>
<?
$docroot = '/usr/local/emhttp';
$plugin = "zfs.master";

require_once "$docroot/webGui/include/Wrappers.php";
require_once "$docroot/webGui/include/publish.php";

require_once $docroot."/plugins/".$plugin."/include/ZFSMHelpers.php";
require_once $docroot."/plugins/".$plugin."/backend/ZFSMOperations.php";

$zfsm_cfg = loadConfig(parse_plugin_cfg($plugin, true));
$zfsm_cfg['version'] = parse_ini_file('/etc/unraid-version')['version'];

function getAllData() {
    $zpool_global = getZFSPools();
    $zpool_devices = array();
    $zpool_datasets = array();

    foreach ($zpool_global as $zpool):
        $zpool_name = $zpool['Pool'];

        $zpool_devices[$zpool_name] = getZFSPoolDevices($zpool_name);
        $zpool_datasets[$zpool_name] = getZFSPoolDatasetsAndSnapshots($zpool_name, $zfsm_cfg['dataset_exclusion']);
        $zpool_global[$zpool_name]['Snapshots'] = $zpool_datasets[$zpool_name]['total_snapshots'];
        $zpool_global[$zpool_name]['MountPoint'] = $zpool_datasets[$zpool_name]['mountpoint'];
    endforeach;

    $message = array();
    $message['data'] = array();
    $message['op'] = "getAll";
    $message['data']['pools'] = $zpool_global;
    $message['data']['devices'] = $zpool_devices;
    $message['data']['datasets'] = $zpool_datasets;

    publish('zfs_master', json_encode($message));
}

function getLazyLoadData() {
    $zpool_global = getZFSPools();
    $zpool_devices = array();
    $zpool_datasets = array();

    foreach ($zpool_global as $zpool):
        $zpool_name = $zpool['Pool'];

        $zpool_devices[$zpool_name] = getZFSPoolDevices($zpool_name);
        $zpool_datasets[$zpool_name] = getZFSPoolDatasets($zpool_name, $zfsm_cfg['dataset_exclusion']);
        $zpool_global[$zpool_name]['Snapshots'] = $zpool_datasets[$zpool_name]['total_snapshots'];
        $zpool_global[$zpool_name]['MountPoint'] = $zpool_datasets[$zpool_name]['mountpoint'];
    endforeach;

    $message = array();
    $message['data'] = array();
    $message['op'] = "getDatasets";
    $message['data']['pools'] = $zpool_global;
    $message['data']['devices'] = $zpool_devices;
    $message['data']['datasets'] = $zpool_datasets;

    publish('zfs_master', json_encode($message));

    foreach ($zpool_datasets as $zpool):
        $message = array();
        $message['data'] = array();
        $message['op'] = "getSnapshot";
        $message['data']['pool'] = $zpool['name'];

        foreach ($zpool['child'] as $zdataset):
            $message['data']['dataset'] = $zdataset['name'];
            $message['data']['snapshots'] = getDatasetSnapshots($zpool['name'], $zdataset['name']);

            publish('zfs_master', json_encode($message));
        endforeach;
    endforeach;
}

while (true) {
    if ($zfsm_cfg['refresh_interval'] == 0):
        if (file_exists('/tmp/zfsm_reload') == true):
            publish('zfs_master', '{"op":"start_refresh"}');

            getAllData();
            
            unlink('/tmp/zfsm_reload');
            publish('zfs_master', '{"op":"stop_refresh"}');
        else:
            usleep(25000); 
        endif;

    elseif ($zfsm_cfg['refresh_interval'] > 0):
        publish('zfs_master', '{"op":"start_refresh"}');
        
        if ($zfsm_cfg['lazy_load'] == false):
            getAllData();
        else:
            getLazyLoadData();
        endif;

        publish('zfs_master', '{"op":"stop_refresh"}');

        sleep($zfsm_cfg['refresh_interval']);
    endif;
}
?>