name: ZFS Master Build

on:
  push:
    branches:
      - beta
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Set base version
        run: |
          if [ "${{ github.ref }}" != "refs/heads/main" ]; then
            echo "buildver=$(date +'%Y.%m.%d').${{ github.run_number }}.${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "buildver=$(date +'%Y.%m.%d').${{ github.run_number }}" >> $GITHUB_ENV
          fi
      - name: Replace version
        run: |
            echo "Replacing current version line"
            sed -i "s/<!ENTITY version.*/<!ENTITY version \"$buildver\">/g" zfs.master.plg
            sed -i "s,IkerSaint/ZFS-Master-Unraid/main,IkerSaint/ZFS-Master-Unraid/${{ github.ref_name }},g" zfs.master.plg
            echo "Done!!"
            cat zfs.master.plg
      - name: Delete other branches releases
        run: |
            find -name 'zfs.master-*.tgz' -type f | grep -v "${{ github.ref_name }}" | xargs -t -I {} rm -f {}
            find -name 'zfs.master-*.tgz' -type f
      - name: Pack the app
        run: |
          echo "Packaging app - zfs.master-$buildver.tgz"
          tar -cvzf zfs.master-$buildver.tgz zfs.master
          echo "Done!!"
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        